In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [7]:
data=pd.read_csv("diabetes.csv")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [9]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [13]:
data.shape

(768, 9)

In [19]:
data.isnull().sum().sum()

0

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [23]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [44]:
Y=data.Outcome

In [46]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [48]:
X=data.drop('Outcome',axis=1)

In [50]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [52]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [66]:
model = LogisticRegression(max_iter=1000)  # Increase max_iter

In [68]:
rfe=RFE(model)

In [70]:
rfe.fit(X,Y)

RFE(estimator=LogisticRegression(max_iter=1000))

In [72]:
rfe.support_

array([ True,  True, False, False, False,  True,  True, False])

In [74]:
selected_indices=[i for i,data in enumerate(rfe.support_) if data==True]
selected_indices

[0, 1, 5, 6]

In [78]:
column_name=X.columns

In [80]:
selected_column_name=[column_name[i] for i in selected_indices]

In [82]:
selected_column_name

['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction']

In [94]:
x=X.loc[:,['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction']]

In [96]:
x

Pregnancies  Glucose   BMI  DiabetesPedigreeFunction
0              6      148  33.6                     0.627
1              1       85  26.6                     0.351
2              8      183  23.3                     0.672
3              1       89  28.1                     0.167
4              0      137  43.1                     2.288
..           ...      ...   ...                       ...
763           10      101  32.9                     0.171
764            2      122  36.8                     0.340
765            5      121  26.2                     0.245
766            1      126  30.1                     0.349
767            1       93  30.4                     0.315

[768 rows x 4 columns]

In [104]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.75,random_state=99)

In [106]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
36            11      138             76              0        0  33.2   
520            2       68             70             32       66  25.0   
275            2      100             70             52       57  40.5   
729            2       92             52              0        0  30.1   
300            0      167              0              0        0  32.3   
..           ...      ...            ...            ...      ...   ...   
713            0      134             58             20      291  26.4   
168            4      110             66              0        0  31.9   
185            7      194             68             28        0  35.9   
35             4      103             60             33      192  24.0   
641            4      128             70              0        0  34.3   

     DiabetesPedigreeFunction  Age  
36                      0.420   35  
520                     0.187   25  
275                     0.677   25  
729                     0.141   22  
300                     0.839   30  
..                        ...  ...  
713                     0.352   21  
168                     0.471   29  
185                     0.745   41  
35                      0.966   33  
641                     0.303   24  

[576 rows x 8 columns]

In [110]:
X_train.shape

(576, 8)

In [112]:
X_test.shape

(192, 8)

In [114]:
Y_train.shape

(576,)

In [116]:
Y_test.shape

(192,)

In [118]:
from sklearn.linear_model import LogisticRegression

In [126]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [128]:
y_pred=lr.predict(X_test)

In [130]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [132]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [136]:
accuracy_score(Y_test,y_pred)

0.7864583333333334

In [138]:
confusion_matrix(Y_test,y_pred)

array([[113,  19],
       [ 22,  38]], dtype=int64)

In [140]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
36            11      138             76              0        0  33.2   
520            2       68             70             32       66  25.0   
275            2      100             70             52       57  40.5   
729            2       92             52              0        0  30.1   
300            0      167              0              0        0  32.3   
..           ...      ...            ...            ...      ...   ...   
713            0      134             58             20      291  26.4   
168            4      110             66              0        0  31.9   
185            7      194             68             28        0  35.9   
35             4      103             60             33      192  24.0   
641            4      128             70              0        0  34.3   

     DiabetesPedigreeFunction  Age  
36                      0.420   35  
520                     0.187   25  
275                     0.677   25  
729                     0.141   22  
300                     0.839   30  
..                        ...  ...  
713                     0.352   21  
168                     0.471   29  
185                     0.745   41  
35                      0.966   33  
641                     0.303   24  

[576 rows x 8 columns]

In [150]:
import warnings
warnings.simplefilter("ignore")

In [152]:
lr.predict([[4,128,70,0,0,34.3,0.303,24]])

array([0], dtype=int64)